VentureCraft/revisionable

readme.md
Modified README with the following change:
In order to maintain a limit on history, but instead of stopping tracking revisions if you want to remove old revisions, you can accomodate that feature by setting `$revisionCleanup`. 
```php
namespace MyApp\Models;
class Article extends Eloquent {
use Venturecraft\Revisionable\RevisionableTrait;
protected $revisionEnabled = true;
protected $revisionCleanup = true; //Remove old revisions (works only when used with $historyLimit)
protected $historyLimit = 500; //Maintain a maximum of 500 changes at any point of time, while cleaning up old revisions.
}
```
=> Modify readme to support removing old revisions

readme.md, src/Venturecraft/Revisionable/Revisionable.php, src/Venturecraft/Revisionable/RevisionableTrait.php
Ability to also track model creations in revisions.
It can be displayed like this:
```
@foreach($user->revisionHistory as $history)
@if($history->key == 'created_at' && !$history->old_value)
<li>Resource was created at {{ $history->new_value }}</li>
@else
<li>{{ ucfirst($history->key) }} changed from {{ $history->old_value }} to {{ $history->new_value }}</li>
@endif
@endforeach
```
=> Added functionality to track model creations

readme.md
VentureCraft, I've corrected a typographical error in the documentation of the [revisionable](https://github.com/VentureCraft/revisionable) project. You should be able to merge this pull request automatically. However, if this was intentional or you enjoy living in linguistic squalor please let me know and [create an issue](https://github.com/thoppe/orthographic-pedant/issues/new) on my home repository.
=> Fixed typographical error, changed accomodate to accommodate in README.

src/Venturecraft/Revisionable/RevisionableTrait.php
This is needed as per restriction in Sentinel User Interface definition
=> Making getUserId to public from private

src/Venturecraft/Revisionable/RevisionableTrait.php
Because SleepingOwl Admin uses its own authentication method, you can't use the stock Auth.
=> Added support for SleepingOwl Admin authentication

src/Venturecraft/Revisionable/Revision.php
(and backward compatible). Also gracefully return false if no class found/doesn't exist, vs. throwing a PHP error about class name
Laravel 5.2 release/upgrade notes have user replace config/auth.php which points to a different location for model.  This causes Revisionable to blow up when calling userResponsible()
See: https://laravel.com/docs/5.2/upgrade#upgrade-5.2.0 + https://github.com/laravel/laravel/blob/master/config/auth.php
Also will fail nicely if the Model can't be found/doesn't found, and returns false early on if no user_id vs. checking classes (nice for the many records where no user_id is provided)
=> Support for Laravel 5.2 in userResponsible() call

src/Venturecraft/Revisionable/FieldFormatter.php
The **datetime** FieldFormatter returns the current time if null passed in. The following changes this to return null as value.
Thanks
=> Update FieldFormatter to handle empty dates

readme.md, src/Venturecraft/Revisionable/RevisionableTrait.php
Added `revisionable.created`, `revisionable.saved` and `revisionable.deleted` events to hook into.
This can be useful if you want to create notifications every time a revisionable model has been edited.
This fixes #108.
=> Added revisionable.* events

src/Venturecraft/Revisionable/RevisionableTrait.php
To avoid clash with the same function name in Sentinel User Model. Fix for <a href="https://github.com/VentureCraft/revisionable/issues/198">Issue#198</a>
=> Change function name from getUserId to getSystemUserId

src/Venturecraft/Revisionable/RevisionableTrait.php
Fixes #222, where the array addition operator overwrites exempted field names between `dontKeep` and `dontKeepRevisionOf` arrays.
=> Fix merging of exempted field arrays

CONTRIBUTING.md, readme.md, src/Venturecraft/Revisionable/Revisionable.php, src/Venturecraft/Revisionable/RevisionableTrait.php
* Events: Added 3 events: revisionable.created, revisionable.saved, and revisionable.deleted
* Morphs: revisionable_type now is set via $this->getMorphClass() instead of get_class($this).
* Fixed issue where keys containing _id but not at the end of the string were considered relationships.
* Fixed hardcoded "deleted_at" column, now respects the getDeletedAtColumn().
* getUserId() has been renamed to getSystemUserId() to prevent issues with others.
* Updated/fixed some logic that could cause breakage. array_merge of do/dontKeep and keepRevisionOf*
* Minor documentation updates.
=> Several updates for new release

src/Venturecraft/Revisionable/RevisionableTrait.php
This fixes an issue where revisions are being added when a field is "null" and is being updated to "null" which is the same value.
=> Use array_key_exists instead of isset

src/Venturecraft/Revisionable/Revision.php
Hi!
The issue linked with this pull request probably has a long history; see, for example, https://github.com/VentureCraft/revisionable/issues/186, https://github.com/VentureCraft/revisionable/pull/279 and https://github.com/sebastienheyd/revisionable/commit/05aedc612d26162ec3882a26c3b5de29145b94f7. It's been almost 1.5 years already. While this pull requests only concerns with removing a single line of code, given the time it took to resolve the issue, I'd like to explain the rationale in detail.
The basic, fundamental issue is:
**When using `Revisionable`, Laravel logs are randomly flooded with `INFO` level messages.**
The messages are neither informative for end users, nor indicative of a failure or wrong usage of the library; however, due to their sheer number, they look frightening …
=> Don't log if nothing is wrong (again)

src/Venturecraft/Revisionable/Revision.php
Hey, me again.
This one is probably a typo.
There's an internal exception which uses `$main_model` as part of its message. The `$main_model` variable initially holds class name of the revisioned model, but is later reassigned to hold an empty instance of the class, causing PHP to serialize the instance. (`__toString()` method calls `toJson()`, which eventually calls `toArray()`).
The problem is, the model might not expect to be serialized when empty, or when not saved (e.g. it may expect a relation to be present). Any exception thrown within `__toString()` method generates an `E_ERROR` ― which is obviously not an exception, but a PHP error, and thus leaks into main application with a rather uninformative error message; like `Method App\Car::__toString() must not throw an exception, caught …
=> Don't serialize empty models

src/Venturecraft/Revisionable/RevisionableTrait.php
using Events::dispatch instead of Events::fire to fix support with laravel 5.8
=> adding compatibility with laravel 5.8

src/Venturecraft/Revisionable/Revision.php
In the App Service Provider I am using
```
Relation::morphMap( [
'posts'         => Post::class,
'prescriptions' => Prescription::class,
'events'        => Event::class,
'feelings'      => Feeling::class,
'troubles'      => Trouble::class,
'stories'       => Story::class
] );
```
Revisionable correctly stores the `reviosionable_type` as `posts` in the DB but when you use the Revionable methods `formatFieldName` and `format` it trys to new up a class called `posts` which doesn't exist. They need to be run through the method `getActualClassNameForMorph` first to see if the class name needs morphing to the full class name.
This fix will only work for Laravel >= 5.2 and welcome to suggestions on how to keep backwards compatibility.
For the meantime if anyone wants to run this they can make …
=> Fix when using morphMap in Laravel >= 5.2

src/Venturecraft/Revisionable/RevisionableTrait.php
Normalization performed by MySQL and discards extra whitespace between keys, values, or elements in the original JSON document. To make lookups more efficient, it sorts the keys of a JSON object.
So it doesn't include if changed only order of Json object key or whitespace after comma
=> Sorts the keys of a JSON object due Normalization performed by MySQL

readme.md, src/Venturecraft/Revisionable/FieldFormatter.php
Analogous to "boolean", only any text or numeric values can act as a source value (often flags are stored in the database). The format allows you to specify different outputs depending on the value.
options: search.On the search|network.In networks
Look at this as an associative array in which the key is separated from the value by a dot. Array elements are separated by a vertical line.
=> Added the output format for values - "options".

.gitignore, readme.md, src/Venturecraft/Revisionable/RevisionableTrait.php, src/config/revisionable.php, tests/RevisionTest.php, tests/migrations/2020_01_02_062329_add_additional_field_to_revisions.php, tests/migrations/2020_01_02_062330_add_additional_field_to_users.php
Howdy!
Our platform tracks more than just user changes since a user can be apart of many accounts. We thought it would be useful to be able to add additional fields to the revision model such that you could be able to see what a user did in any given account. 
- We added a test to make sure none of this breaks the original awesome functionality.
- We used the config file and native PHP data types to make it easy to specify which additional columns should be included in the model.
- We added some documentation to the readme to make sure people utilizing this additional functionality know how to do it,.
- We added a test, `testRevisionSkipsAdditionalFieldsWhenMisconfigured()` to make sure that if  someone makes a mistake, we don't break their functionality.
We really appreciate all the hard …
=> Ability to add aditional fields

src/migrations/2013_04_09_062329_create_revisions_table.php
use larger integers for ID's and in down function change to dropIfExists, to prevent a potential failure
=> use newer conventions

readme.md, src/Venturecraft/Revisionable/FieldFormatter.php, src/Venturecraft/Revisionable/Revisionable.php, src/Venturecraft/Revisionable/RevisionableTrait.php
Hello! 
Many users have asked to add a force delete model save. I also use this in my projects. 
I think I have found a solution and I offer it to you. It is very simple. We will save `created_at` field as the key, and the values: `oldValue` it is the `created_at` field, newValue it is `null`. That is, this behavior is completely opposite to preserving the creation of the model. 
I described everything in the README. Please take a look.
=> Added storing Force Delete

src/Venturecraft/Revisionable/RevisionableTrait.php
**  Re-posting to the master branch since "develope" seems to be way behind.
I recently upgraded from version 1.30.0 to 1.34.0 and found that a change to preSave() in 1.31.1 to check the attribute cast caused a problem with another trait. We use an encryptable attribute trait on our models to encrypt values before they are stored in the database. Some of these values are also cast as arrays. The order of operations of the traits causes the values cast as array to be encrypted before Revisionable can act on the update events.
The change to preSave() checks each model attribute to see if it's cast as an object so the key order can be normalized. However, it doesn't verify the value is actually an object or array before using json_decode/json_encode. Because the attribute was already …
=> checks value is object before using json_decode() in preSave()

src/Venturecraft/Revisionable/Revisionable.php
I'm using Lumen 5.8 and this call fails with Config class not found. However, using \Config elsewhere works and importing the facade works too.
Regardless, this is a better way to resolve the config and is already used elsewhere in the app.
Thanks!
=> Revert #112 and follow #113
